# Generated by Django 4.1.4 on 2022-12-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_alter_option_options_alter_riddle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterField(
            model_name='option',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Верный вариант ответа'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст варианта ответа'),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации загадки'),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='riddle_text',
            field=models.CharField(max_length=255, verbose_name='Текст загадки'),
        ),
    ]
